# Generated by Django 5.2.14 on 2026-05-16 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(upload_to='importaciones/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('hoja', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('completada', 'Completada'), ('error', 'Error')], default='procesando', max_length=30)),
                ('total_filas', models.PositiveIntegerField(default=0)),
                ('creados', models.PositiveIntegerField(default=0)),
                ('actualizados', models.PositiveIntegerField(default=0)),
                ('omitidos', models.PositiveIntegerField(default=0)),
                ('errores', models.JSONField(blank=True, default=list)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('comuna', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, default='La Araucania', max_length=120)),
                ('origen', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'comuna'), name='uniq_comite_nombre_comuna')],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rut', models.CharField(db_index=True, max_length=16, unique=True)),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('sexo', models.CharField(blank=True, max_length=30)),
                ('estado_civil', models.CharField(blank=True, max_length=80)),
                ('nacionalidad', models.CharField(blank=True, max_length=80)),
                ('etnia', models.CharField(blank=True, max_length=120)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('persona_mayor', models.BooleanField(default=False)),
                ('discapacidad', models.BooleanField(default=False)),
                ('neurodivergencia', models.BooleanField(default=False)),
                ('estado_general', models.CharField(choices=[('apta', 'Apta'), ('observada', 'Observada'), ('bloqueada', 'Bloqueada')], db_index=True, default='apta', max_length=20)),
                ('datos_originales', models.JSONField(blank=True, default=dict)),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='habitacional.comite')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField()),
                ('autor', models.CharField(blank=True, max_length=120)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='habitacional.persona')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('cedula', 'Cedula'), ('libreta', 'Libreta'), ('rsh', 'RSH'), ('discapacidad', 'Discapacidad'), ('otro', 'Otro')], max_length=40)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('por_vencer', 'Por vencer'), ('vencido', 'Vencido'), ('no_informado', 'No informado')], default='no_informado', max_length=40)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('observaciones', models.TextField(blank=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='habitacional.persona')),
            ],
            options={
                'ordering': ['tipo', 'fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='CaracterizacionSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('comuna', models.CharField(blank=True, max_length=120)),
                ('parentesco', models.CharField(blank=True, max_length=120)),
                ('tipo_familia', models.CharField(blank=True, max_length=120)),
                ('integrantes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caracterizacion_social', to='habitacional.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('documental', 'Documental'), ('social', 'Social'), ('financiera', 'Financiera'), ('rsh', 'RSH'), ('sistema', 'Sistema')], max_length=40)),
                ('severidad', models.CharField(choices=[('preventiva', 'Preventiva'), ('critica', 'Critica')], max_length=40)),
                ('titulo', models.CharField(max_length=180)),
                ('detalle', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('origen', models.CharField(blank=True, default='manual', max_length=80)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='habitacional.persona')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Ahorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=80)),
                ('banco', models.CharField(blank=True, max_length=120)),
                ('monto_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ahorro_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_corte', models.DateField(blank=True, null=True)),
                ('insuficiente', models.BooleanField(default=False)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ahorro', to='habitacional.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('programa', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(blank=True, max_length=120)),
                ('minvu_conecta', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postulacion', to='habitacional.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RSH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tramo', models.CharField(blank=True, max_length=80)),
                ('es_preferente', models.BooleanField(default=False)),
                ('fuente', models.CharField(blank=True, default='Excel', max_length=120)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rsh', to='habitacional.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['nombre'], name='habitaciona_nombre_a832e3_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['telefono'], name='habitaciona_telefon_af0fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['estado_general'], name='habitaciona_estado__89a726_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tipo', 'estado'], name='habitaciona_tipo_a55452_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['fecha_vencimiento'], name='habitaciona_fecha_v_f8bb5b_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['activa', 'severidad'], name='habitaciona_activa_c53941_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['tipo'], name='habitaciona_tipo_d4aba5_idx'),
        ),
    ]
