# Generated by Django 5.2.14 on 2026-05-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacional', '0004_caracterizacionsocial_hijos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('cedula', 'Cédula'), ('libreta', 'Libreta'), ('rsh', 'RSH'), ('discapacidad', 'Discapacidad'), ('otro', 'Otro')], max_length=40),
        ),
    ]
