# Generated by Django 5.2.14 on 2026-09-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacional', '0005_alter_documento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPostventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('rut', models.CharField(db_index=True, max_length=16)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('comite_nombre', models.CharField(blank=True, max_length=255)),
                ('vivienda_direccion', models.CharField(blank=True, max_length=255)),
                ('recinto', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='postventa/fotos/%Y/%m/')),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('en_gestion', 'En gestión'), ('resuelta', 'Resuelta')], db_index=True, default='recibida', max_length=20)),
                ('urgencia', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente')], db_index=True, default='normal', max_length=20)),
                ('respuesta_tecnica', models.TextField(blank=True)),
                ('tecnico_responsable', models.CharField(blank=True, max_length=150)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['rut'], name='habitaciona_rut_16f2cb_idx'), models.Index(fields=['estado'], name='habitaciona_estado_820101_idx'), models.Index(fields=['urgencia'], name='habitaciona_urgenci_c8a012_idx')],
            },
        ),
    ]
