# Generated by Django 5.2.14 on 2026-10-01 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacional', '0006_ticketpostventa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rol', models.CharField(choices=[('admin', 'Administrador / Soporte'), ('coordinador', 'Coordinador General / Gerencia'), ('social', 'Profesional Área Social'), ('tecnico', 'Profesional Área Técnica')], db_index=True, default='social', max_length=20)),
                ('nombre_completo', models.CharField(blank=True, max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario__username'],
            },
        ),
    ]
