# Generated by Django 5.2.14 on 2026-10-01 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacional', '0007_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre_autor', models.CharField(blank=True, max_length=255)),
                ('correo_autor', models.EmailField(blank=True, max_length=254)),
                ('rol_autor', models.CharField(blank=True, max_length=50)),
                ('modulo', models.CharField(max_length=150)),
                ('ruta', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(choices=[('mejora', 'Sugerencia de Mejora'), ('problema', 'Reporte de Problema / Observación'), ('idea', 'Nueva Funcionalidad')], default='mejora', max_length=30)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'En Revisión'), ('implementado', 'Implementada'), ('descartado', 'Descartada')], default='pendiente', max_length=30)),
                ('respuesta_soporte', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
