# Generated by Django 5.2.14 on 2026-10-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacional', '0008_sugerenciafeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='comite',
            name='decreto',
            field=models.CharField(choices=[('DS49', 'DS49 · Fondo Solidario de Elección de Vivienda'), ('DS01', 'DS01 · Sectores Medios (Tramos 1, 2 y 3)'), ('DS19', 'DS19 · Integración Social y Territorial'), ('DS27', 'DS27 · Mejoramiento de Vivienda y Barrios'), ('DS10', 'DS10 · Habitabilidad Rural')], db_index=True, default='DS49', max_length=20),
        ),
        migrations.AddField(
            model_name='importacionexcel',
            name='decreto',
            field=models.CharField(blank=True, choices=[('DS49', 'DS49 · Fondo Solidario de Elección de Vivienda'), ('DS01', 'DS01 · Sectores Medios (Tramos 1, 2 y 3)'), ('DS19', 'DS19 · Integración Social y Territorial'), ('DS27', 'DS27 · Mejoramiento de Vivienda y Barrios'), ('DS10', 'DS10 · Habitabilidad Rural')], default='DS49', max_length=20),
        ),
    ]
