# Generated by Django 5.2.14 on 2026-10-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacional', '0009_comite_decreto_importacionexcel_decreto'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['persona', 'activa', 'impacta_estado'], name='idx_alerta_p_act_imp'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['persona', 'activa', 'severidad'], name='idx_alerta_p_act_sev'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['comite', 'estado_general'], name='idx_pers_comite_est'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['comite', 'persona_mayor'], name='idx_pers_comite_may'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['comite', 'discapacidad'], name='idx_pers_comite_disc'),
        ),
    ]
